### ISSUE TITLE
An issue with teleporting.

### ISSUE THREAD

**Issue by kerneljay** [Sleepless-Development/sleepless_pedmanager#1]
I would love if you created a function/exports to delete all markers.

I have an issue when teleporting, the marker sticks on the screen and doesnt delete

![image](https://github.com/Demigod916/demi-pedmanager/assets/116266395/6584731c-cf22-4104-b833-ce2e4aca8d54)

**Comment by DemiAutomatic** [comment]
Rather than add this export, i will just fix the issue that causes this instead. 

@Jays-Scripts send me the full entry for this ped so i can replicate the issue

**Comment by DemiAutomatic** [comment]
@Jays-Scripts this is now fixed in v2.0.1
